export const projects = [
  {
    title: 'Cryptocurrency App',
    description: "",
      image: '/images/projectImage.png',
      tags: ['React', 'Redux Toolkit', 'Rapid API', 'Ant Design'],
    source: 'https://github.com/firas-debich/kryptoApp',
    visit: 'https://firas-debich.github.io/kryptoApp/',
    id: 0,
  },
  {
    title: ' Travel Companion ',
    description: "",
    image: '/images/1.png',
    tags: ['React', 'Rapid API', 'Material UI', 'Google API'],
    source: 'https://github.com/firas-debich/travel.github.io',
    visit: 'https://firas-debich.github.io/travel.github.io/',
    id: 0,
  },
  {
    title: 'Chrome Extension',
    description:"",
    image: '/images/2.png',
    tags: ['JavaScript',"Html 5","CSS 3"],
    source: 'https://github.com/firas-debich/chrome-extension',
    visit: 'https://github.com/firas-debich/chrome-extension',
    id: 1,
  },
  {
    title: 'Blockchain App',
    description:"",
    image: '/images/bc.png',
    tags: ['React',"Tailwind CSS","Solidity","web 3"],
    source: 'https://github.com/firas-debich/Blockchain-App',
    visit: 'https://firas-debich.github.io/Blockchain-App/',
    id: 1,
  },
  {
    title: 'Carx',
    description: "A team Project where we Developed a mobile application that allows car users to ask for an agent to clean their car where ever they are.",
      image: '/images/carXProject.png',
      tags: ['React Native', 'Tailwind css',"Nest Js","PostgreSQL"],
    source: 'https://github.com/firas-debich/carX',
    visit: 'https://expo.dev/artifacts/b7481cbc-d12e-4968-8e7c-1b07c907c1b2',
    id: 2,
  },
  {
    title: 'UberEats Clone',
    description: "",
    image: '/images/4.png',
    tags: ['React Native', 'Google Places', 'Firebase'],
    source: 'https://github.com/firas-debich/react-native-Uber-Eats-clone/tree/main',
    visit: 'https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/android/%40firas_debich/UberEats-602025d23a45443b97518d82ff703a74-signed.apk',
    id: 3,
  },
];

export const TimeLineData = [
  { year: "08/2020", text: 'got My Baccalaureat', },
  { year: "11/2021", text: 'Got my certificate as a full stack JS developer'},
  { year: "6/2022", text: 'Start my journey at AWS re/Start Program'},
]; 